feat(DCOS-15073): Ensure script finds the volumes to delete

diff --git a/system-tests/services/_scripts/external-volumes/setup b/system-tests/services/_scripts/external-volumes/setup
--- a/system-tests/services/_scripts/external-volumes/setup
+++ b/system-tests/services/_scripts/external-volumes/setup
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ -z "$NUM_TESTS" ]; then
+  echo "Error: Please specify the NUM_TESTS environment variable"
+  exit 1
+fi
+
 if [ -z "$REGION" ]; then
   echo "Error: Please specify the REGION environment variable"
   exit 1
